name: infra-iac

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra-iac.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'
  workflow_dispatch:
    inputs:
      apply:
        description: 'Apply Terraform changes?'
        required: true
        type: choice
        options: ['false', 'true']
        default: 'false'

permissions:
  id-token: write
  contents: read
  security-events: write

concurrency:
  group: infra-iac
  cancel-in-progress: false

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
  TF_STATE_LOCK_TABLE: ${{ vars.TF_STATE_LOCK_TABLE }}
  TF_STATE_KEY: infra/terraform.tfstate
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  TF_VAR_admin_cidr: ${{ vars.ADMIN_CIDR }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials by OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}" \
            -backend-config="encrypt=true"

      - name: Terraform validate
        run: terraform validate

      - name: IaC security scan - Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra
          quiet: true
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,checkov.sarif
          skip_check: CKV_AWS_18,CKV_AWS_20,CKV_AWS_24,CKV_AWS_41,CKV_AWS_79,CKV_AWS_356

      - name: Upload Checkov SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: github.event_name == 'workflow_dispatch' && inputs.apply == 'true' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
