name: infra-iac

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply Terraform changes?"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/infra-iac.yml"

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
  TF_STATE_LOCK_TABLE: ${{ vars.TF_STATE_LOCK_TABLE }}
  ADMIN_CIDR: ${{ vars.ADMIN_CIDR }}

jobs:
  terraform:
    name: Terraform IaC Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform format
        run: terraform fmt -recursive

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=wiz-aws-devsecops-lab/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}" \
            -backend-config="encrypt=true"

      - name: Terraform validate
        run: terraform validate

      - name: Run Checkov IaC scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,checkov.sarif
          soft_fail: true

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always() && hashFiles('checkov.sarif') != ''
        with:
          sarif_file: checkov.sarif

      - name: Terraform plan
        run: |
          terraform plan \
            -var="aws_region=${AWS_REGION}" \
            -var="admin_cidr=${ADMIN_CIDR}" \
            -out=tfplan

      - name: Terraform apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true'
        run: terraform apply -auto-approve tfplan
